# This is the final, simplified configuration for a JavaScript project on Netlify.

[build]
  # This tells Netlify where your main website files are.
  publish = "."

[functions]
  # This tells Netlify where your JavaScript function code lives.
  directory = "netlify/functions"

# This redirect rule connects your website's API calls to the function.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
