[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  included_files = ["./**"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200