# This is the final, simplified configuration for Netlify.
# It relies on Netlify's automatic dependency installation.

[build]
  # The publish directory is the root of your project where index.html lives.
  publish = "."

[functions]
  # This tells Netlify where to find the function files.
  directory = "netlify/functions"

# This redirect rule connects your website's API calls to the function.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
