[build]
  # The publish directory is the root of your project where index.html lives.
  publish = "."

[functions]
  # This specifies the directory where your function files are.
  directory = "netlify/functions"
  # This line is the key fix. It tells the bundler to not include
  # 'play-dl' in the function bundle, and instead make it available
  # at runtime. This resolves the build error.
  external_node_modules = ["play-dl"]
  node_bundler = "esbuild"

# This redirect rule connects your website's API calls to the function.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
