# This is the final, definitive configuration for a JavaScript project on Netlify.
# It uses the 'zisi' bundler which is more robust for including dependencies.

[build]
  # This tells Netlify where your main website files are.
  publish = "."

[functions]
  # This tells Netlify where your JavaScript function code lives.
  directory = "netlify/functions"
  # This line is the key fix. It switches to a more robust bundler.
  node_bundler = "zisi"

# This redirect rule is essential. It connects your website's API calls 
# to the actual function files.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
