[build]
  # The publish directory is the root of your project where index.html lives.
  publish = "."

[functions]
  # This specifies the directory where your function files are.
  directory = "netlify/functions"
  # This line is the key fix. We are switching to the 'zisi' bundler,
  # which is more robust at handling complex dependencies like 'play-dl'.
  node_bundler = "zisi"

# This redirect rule connects your website's API calls to the function.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
